// <auto-generated />
using System;
using EduConnect.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EduConnect.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260322133156_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EduConnect.Api.Entities.Administrador", b =>
                {
                    b.Property<int>("AdministradorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdministradorId"));

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Registro")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("AdministradorId");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Administradores");
                });

            modelBuilder.Entity("EduConnect.Api.Entities.AgendaEvento", b =>
                {
                    b.Property<int>("AgendaEventoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AgendaEventoId"));

                    b.Property<int>("CriadoPorProfessorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataEvento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("TurmaId")
                        .HasColumnType("int");

                    b.HasKey("AgendaEventoId");

                    b.HasIndex("CriadoPorProfessorId");

                    b.HasIndex("TurmaId");

                    b.ToTable("EventosAgenda");
                });

            modelBuilder.Entity("EduConnect.Api.Entities.Aluno", b =>
                {
                    b.Property<int>("AlunoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AlunoId"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("FotoUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Registro")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorMensalPadrao")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("AlunoId");

                    b.HasIndex("Registro")
                        .IsUnique();

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("EduConnect.Api.Entities.Disciplina", b =>
                {
                    b.Property<int>("DisciplinaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DisciplinaId"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("NivelEnsinoId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("DisciplinaId");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("NivelEnsinoId");

                    b.ToTable("Disciplinas");
                });

            modelBuilder.Entity("EduConnect.Api.Entities.Frequencia", b =>
                {
                    b.Property<int>("FrequenciaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FrequenciaId"));

                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAula")
                        .HasColumnType("date");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisciplinaId")
                        .HasColumnType("int");

                    b.Property<string>("Observacao")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("Presente")
                        .HasColumnType("bit");

                    b.Property<int>("RegistradoPorProfessorId")
                        .HasColumnType("int");

                    b.Property<int>("TurmaId")
                        .HasColumnType("int");

                    b.HasKey("FrequenciaId");

                    b.HasIndex("AlunoId");

                    b.HasIndex("DisciplinaId");

                    b.HasIndex("RegistradoPorProfessorId");

                    b.HasIndex("TurmaId", "AlunoId", "DisciplinaId", "DataAula")
                        .IsUnique();

                    b.ToTable("Frequencias");
                });

            modelBuilder.Entity("EduConnect.Api.Entities.InteresseMatricula", b =>
                {
                    b.Property<int>("InteresseMatriculaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InteresseMatriculaId"));

                    b.Property<string>("AnoEscolarAtual")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("DataNascimentoAluno")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataNascimentoResponsavel")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataSolicitacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentoAlunoUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("DocumentoResponsavelUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("EmailContato")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NomeAluno")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NomeResponsavel")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("InteresseMatriculaId");

                    b.ToTable("InteressesMatricula");
                });

            modelBuilder.Entity("EduConnect.Api.Entities.MaterialApoio", b =>
                {
                    b.Property<int>("MaterialApoioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaterialApoioId"));

                    b.Property<string>("ArquivoUrl")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("DataPublicacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("TurmaId")
                        .HasColumnType("int");

                    b.HasKey("MaterialApoioId");

                    b.HasIndex("ProfessorId");

                    b.HasIndex("TurmaId");

                    b.ToTable("MateriaisApoio");
                });

            modelBuilder.Entity("EduConnect.Api.Entities.Mensalidade", b =>
                {
                    b.Property<int>("MensalidadeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MensalidadeId"));

                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<string>("Competencia")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<DateTime?>("DataPagamento")
                        .HasColumnType("date");

                    b.Property<DateTime>("DataVencimento")
                        .HasColumnType("date");

                    b.Property<string>("Observacao")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("ResponsavelId")
                        .HasColumnType("int");

                    b.Property<string>("StatusPagamento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("MensalidadeId");

                    b.HasIndex("ResponsavelId");

                    b.HasIndex("AlunoId", "Competencia")
                        .IsUnique();

                    b.ToTable("Mensalidades");
                });

            modelBuilder.Entity("EduConnect.Api.Entities.NivelEnsino", b =>
                {
                    b.Property<int>("NivelEnsinoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NivelEnsinoId"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("NivelEnsinoId");

                    b.ToTable("NiveisEnsino");
                });

            modelBuilder.Entity("EduConnect.Api.Entities.Nota", b =>
                {
                    b.Property<int>("NotaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotaId"));

                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataLancamento")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisciplinaId")
                        .HasColumnType("int");

                    b.Property<int>("LancadoPorProfessorId")
                        .HasColumnType("int");

                    b.Property<string>("TipoAvaliacao")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("TurmaId")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("NotaId");

                    b.HasIndex("DisciplinaId");

                    b.HasIndex("LancadoPorProfessorId");

                    b.HasIndex("TurmaId");

                    b.HasIndex("AlunoId", "TurmaId", "DisciplinaId", "TipoAvaliacao")
                        .IsUnique();

                    b.ToTable("Notas", t =>
                        {
                            t.HasCheckConstraint("CK_Nota_Valor", "[Valor] >= 0 AND [Valor] <= 10");
                        });
                });

            modelBuilder.Entity("EduConnect.Api.Entities.NotaHistorico", b =>
                {
                    b.Property<int>("NotaHistoricoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotaHistoricoId"));

                    b.Property<int>("AlteradoPorUsuarioId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Motivo")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("NotaId")
                        .HasColumnType("int");

                    b.Property<decimal>("ValorAnterior")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("ValorNovo")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("NotaHistoricoId");

                    b.HasIndex("AlteradoPorUsuarioId");

                    b.HasIndex("NotaId");

                    b.ToTable("NotasHistorico");
                });

            modelBuilder.Entity("EduConnect.Api.Entities.Notificacao", b =>
                {
                    b.Property<int>("NotificacaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificacaoId"));

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataLeitura")
                        .HasColumnType("datetime2");

                    b.Property<int>("DestinatarioUsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("EntidadeReferencia")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("EntidadeReferenciaId")
                        .HasColumnType("int");

                    b.Property<bool>("Lida")
                        .HasColumnType("bit");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("RemetenteUsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Titulo")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("NotificacaoId");

                    b.HasIndex("RemetenteUsuarioId");

                    b.HasIndex("DestinatarioUsuarioId", "Lida", "DataEnvio");

                    b.ToTable("Notificacoes");
                });

            modelBuilder.Entity("EduConnect.Api.Entities.Ocorrencia", b =>
                {
                    b.Property<int>("OcorrenciaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OcorrenciaId"));

                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataOcorrencia")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("int");

                    b.Property<int>("TurmaId")
                        .HasColumnType("int");

                    b.HasKey("OcorrenciaId");

                    b.HasIndex("AlunoId");

                    b.HasIndex("ProfessorId");

                    b.HasIndex("TurmaId");

                    b.ToTable("Ocorrencias");
                });

            modelBuilder.Entity("EduConnect.Api.Entities.Perfil", b =>
                {
                    b.Property<int>("PerfilId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PerfilId"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("PerfilId");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("Perfis");
                });

            modelBuilder.Entity("EduConnect.Api.Entities.Professor", b =>
                {
                    b.Property<int>("ProfessorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProfessorId"));

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailInstitucional")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Registro")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("ProfessorId");

                    b.HasIndex("EmailInstitucional")
                        .IsUnique();

                    b.HasIndex("Registro")
                        .IsUnique();

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Professores");
                });

            modelBuilder.Entity("EduConnect.Api.Entities.ProfessorDisciplina", b =>
                {
                    b.Property<int>("ProfessorDisciplinaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProfessorDisciplinaId"));

                    b.Property<int>("CargaHorariaSemanal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("DisciplinaId")
                        .HasColumnType("int");

                    b.Property<int>("NivelEnsinoId")
                        .HasColumnType("int");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("int");

                    b.HasKey("ProfessorDisciplinaId");

                    b.HasIndex("DisciplinaId");

                    b.HasIndex("NivelEnsinoId");

                    b.HasIndex("ProfessorId", "DisciplinaId", "NivelEnsinoId")
                        .IsUnique();

                    b.ToTable("ProfessoresDisciplinas", t =>
                        {
                            t.HasCheckConstraint("CK_ProfessorDisciplina_CargaHoraria", "[CargaHorariaSemanal] >= 0 AND [CargaHorariaSemanal] <= 40");
                        });
                });

            modelBuilder.Entity("EduConnect.Api.Entities.Publicacao", b =>
                {
                    b.Property<int>("PublicacaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PublicacaoId"));

                    b.Property<int>("AdministradorId")
                        .HasColumnType("int");

                    b.Property<bool>("Ativa")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataPublicacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("PublicacaoId");

                    b.HasIndex("AdministradorId");

                    b.ToTable("Publicacoes");
                });

            modelBuilder.Entity("EduConnect.Api.Entities.Responsavel", b =>
                {
                    b.Property<int>("ResponsavelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResponsavelId"));

                    b.Property<string>("EmailContato")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Registro")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("ResponsavelId");

                    b.HasIndex("Registro")
                        .IsUnique();

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("Responsaveis");
                });

            modelBuilder.Entity("EduConnect.Api.Entities.ResponsavelAluno", b =>
                {
                    b.Property<int>("ResponsavelAlunoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResponsavelAlunoId"));

                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<bool>("Principal")
                        .HasColumnType("bit");

                    b.Property<int>("ResponsavelId")
                        .HasColumnType("int");

                    b.Property<string>("TipoResponsabilidade")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("ResponsavelAlunoId");

                    b.HasIndex("AlunoId");

                    b.HasIndex("ResponsavelId", "AlunoId")
                        .IsUnique();

                    b.ToTable("ResponsaveisAlunos");
                });

            modelBuilder.Entity("EduConnect.Api.Entities.Turma", b =>
                {
                    b.Property<int>("TurmaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TurmaId"));

                    b.Property<int>("AnoLetivo")
                        .HasColumnType("int");

                    b.Property<bool>("Ativa")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataValidade")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("NivelEnsinoId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProfessorTutorNome")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Sala")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("TurmaId");

                    b.HasIndex("NivelEnsinoId");

                    b.HasIndex("Nome", "AnoLetivo")
                        .IsUnique();

                    b.ToTable("Turmas");
                });

            modelBuilder.Entity("EduConnect.Api.Entities.TurmaAluno", b =>
                {
                    b.Property<int>("TurmaAlunoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TurmaAlunoId"));

                    b.Property<int>("AlunoId")
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataEntrada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataSaida")
                        .HasColumnType("datetime2");

                    b.Property<int>("TurmaId")
                        .HasColumnType("int");

                    b.HasKey("TurmaAlunoId");

                    b.HasIndex("AlunoId");

                    b.HasIndex("TurmaId", "AlunoId", "Ativo");

                    b.ToTable("TurmasAluno");
                });

            modelBuilder.Entity("EduConnect.Api.Entities.TurmaProfessorDisciplina", b =>
                {
                    b.Property<int>("TurmaProfessorDisciplinaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TurmaProfessorDisciplinaId"));

                    b.Property<DateTime>("DataVinculo")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisciplinaId")
                        .HasColumnType("int");

                    b.Property<int>("ProfessorId")
                        .HasColumnType("int");

                    b.Property<int>("TurmaId")
                        .HasColumnType("int");

                    b.Property<int>("VinculadoPorUsuarioId")
                        .HasColumnType("int");

                    b.HasKey("TurmaProfessorDisciplinaId");

                    b.HasIndex("DisciplinaId");

                    b.HasIndex("ProfessorId");

                    b.HasIndex("VinculadoPorUsuarioId");

                    b.HasIndex("TurmaId", "ProfessorId")
                        .IsUnique();

                    b.ToTable("TurmasProfessoresDisciplinas");
                });

            modelBuilder.Entity("EduConnect.Api.Entities.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("PerfilId")
                        .HasColumnType("int");

                    b.Property<string>("Registro")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UltimoAcesso")
                        .HasColumnType("datetime2");

                    b.HasKey("UsuarioId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PerfilId");

                    b.HasIndex("Registro")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("EduConnect.Api.Entities.Administrador", b =>
                {
                    b.HasOne("EduConnect.Api.Entities.Usuario", "Usuario")
                        .WithOne("Administrador")
                        .HasForeignKey("EduConnect.Api.Entities.Administrador", "UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EduConnect.Api.Entities.AgendaEvento", b =>
                {
                    b.HasOne("EduConnect.Api.Entities.Professor", "CriadoPorProfessor")
                        .WithMany()
                        .HasForeignKey("CriadoPorProfessorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EduConnect.Api.Entities.Turma", "Turma")
                        .WithMany("EventosAgenda")
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CriadoPorProfessor");

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("EduConnect.Api.Entities.Aluno", b =>
                {
                    b.HasOne("EduConnect.Api.Entities.Usuario", "Usuario")
                        .WithOne("Aluno")
                        .HasForeignKey("EduConnect.Api.Entities.Aluno", "UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EduConnect.Api.Entities.Disciplina", b =>
                {
                    b.HasOne("EduConnect.Api.Entities.NivelEnsino", "NivelEnsino")
                        .WithMany("Disciplinas")
                        .HasForeignKey("NivelEnsinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NivelEnsino");
                });

            modelBuilder.Entity("EduConnect.Api.Entities.Frequencia", b =>
                {
                    b.HasOne("EduConnect.Api.Entities.Aluno", "Aluno")
                        .WithMany("Frequencias")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EduConnect.Api.Entities.Disciplina", "Disciplina")
                        .WithMany()
                        .HasForeignKey("DisciplinaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EduConnect.Api.Entities.Professor", "RegistradoPorProfessor")
                        .WithMany()
                        .HasForeignKey("RegistradoPorProfessorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EduConnect.Api.Entities.Turma", "Turma")
                        .WithMany()
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Disciplina");

                    b.Navigation("RegistradoPorProfessor");

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("EduConnect.Api.Entities.MaterialApoio", b =>
                {
                    b.HasOne("EduConnect.Api.Entities.Professor", "Professor")
                        .WithMany()
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EduConnect.Api.Entities.Turma", "Turma")
                        .WithMany("MateriaisApoio")
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Professor");

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("EduConnect.Api.Entities.Mensalidade", b =>
                {
                    b.HasOne("EduConnect.Api.Entities.Aluno", "Aluno")
                        .WithMany()
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EduConnect.Api.Entities.Responsavel", "Responsavel")
                        .WithMany("Mensalidades")
                        .HasForeignKey("ResponsavelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("EduConnect.Api.Entities.Nota", b =>
                {
                    b.HasOne("EduConnect.Api.Entities.Aluno", "Aluno")
                        .WithMany("Notas")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EduConnect.Api.Entities.Disciplina", "Disciplina")
                        .WithMany()
                        .HasForeignKey("DisciplinaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EduConnect.Api.Entities.Professor", "LancadoPorProfessor")
                        .WithMany()
                        .HasForeignKey("LancadoPorProfessorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EduConnect.Api.Entities.Turma", "Turma")
                        .WithMany()
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Disciplina");

                    b.Navigation("LancadoPorProfessor");

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("EduConnect.Api.Entities.NotaHistorico", b =>
                {
                    b.HasOne("EduConnect.Api.Entities.Usuario", "AlteradoPorUsuario")
                        .WithMany()
                        .HasForeignKey("AlteradoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EduConnect.Api.Entities.Nota", "Nota")
                        .WithMany("Historico")
                        .HasForeignKey("NotaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AlteradoPorUsuario");

                    b.Navigation("Nota");
                });

            modelBuilder.Entity("EduConnect.Api.Entities.Notificacao", b =>
                {
                    b.HasOne("EduConnect.Api.Entities.Usuario", "DestinatarioUsuario")
                        .WithMany("NotificacoesRecebidas")
                        .HasForeignKey("DestinatarioUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EduConnect.Api.Entities.Usuario", "RemetenteUsuario")
                        .WithMany("NotificacoesEnviadas")
                        .HasForeignKey("RemetenteUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DestinatarioUsuario");

                    b.Navigation("RemetenteUsuario");
                });

            modelBuilder.Entity("EduConnect.Api.Entities.Ocorrencia", b =>
                {
                    b.HasOne("EduConnect.Api.Entities.Aluno", "Aluno")
                        .WithMany("Ocorrencias")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EduConnect.Api.Entities.Professor", "Professor")
                        .WithMany()
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EduConnect.Api.Entities.Turma", "Turma")
                        .WithMany()
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Professor");

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("EduConnect.Api.Entities.Professor", b =>
                {
                    b.HasOne("EduConnect.Api.Entities.Usuario", "Usuario")
                        .WithOne("Professor")
                        .HasForeignKey("EduConnect.Api.Entities.Professor", "UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EduConnect.Api.Entities.ProfessorDisciplina", b =>
                {
                    b.HasOne("EduConnect.Api.Entities.Disciplina", "Disciplina")
                        .WithMany("ProfessorDisciplinas")
                        .HasForeignKey("DisciplinaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EduConnect.Api.Entities.NivelEnsino", "NivelEnsino")
                        .WithMany()
                        .HasForeignKey("NivelEnsinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EduConnect.Api.Entities.Professor", "Professor")
                        .WithMany("ProfessorDisciplinas")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Disciplina");

                    b.Navigation("NivelEnsino");

                    b.Navigation("Professor");
                });

            modelBuilder.Entity("EduConnect.Api.Entities.Publicacao", b =>
                {
                    b.HasOne("EduConnect.Api.Entities.Administrador", "Administrador")
                        .WithMany()
                        .HasForeignKey("AdministradorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Administrador");
                });

            modelBuilder.Entity("EduConnect.Api.Entities.Responsavel", b =>
                {
                    b.HasOne("EduConnect.Api.Entities.Usuario", "Usuario")
                        .WithOne("Responsavel")
                        .HasForeignKey("EduConnect.Api.Entities.Responsavel", "UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("EduConnect.Api.Entities.ResponsavelAluno", b =>
                {
                    b.HasOne("EduConnect.Api.Entities.Aluno", "Aluno")
                        .WithMany("ResponsaveisAlunos")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EduConnect.Api.Entities.Responsavel", "Responsavel")
                        .WithMany("ResponsaveisAlunos")
                        .HasForeignKey("ResponsavelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("EduConnect.Api.Entities.Turma", b =>
                {
                    b.HasOne("EduConnect.Api.Entities.NivelEnsino", "NivelEnsino")
                        .WithMany("Turmas")
                        .HasForeignKey("NivelEnsinoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NivelEnsino");
                });

            modelBuilder.Entity("EduConnect.Api.Entities.TurmaAluno", b =>
                {
                    b.HasOne("EduConnect.Api.Entities.Aluno", "Aluno")
                        .WithMany("TurmasAluno")
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EduConnect.Api.Entities.Turma", "Turma")
                        .WithMany("TurmasAluno")
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Aluno");

                    b.Navigation("Turma");
                });

            modelBuilder.Entity("EduConnect.Api.Entities.TurmaProfessorDisciplina", b =>
                {
                    b.HasOne("EduConnect.Api.Entities.Disciplina", "Disciplina")
                        .WithMany("TurmaProfessorDisciplinas")
                        .HasForeignKey("DisciplinaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EduConnect.Api.Entities.Professor", "Professor")
                        .WithMany("TurmaProfessorDisciplinas")
                        .HasForeignKey("ProfessorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EduConnect.Api.Entities.Turma", "Turma")
                        .WithMany("TurmaProfessorDisciplinas")
                        .HasForeignKey("TurmaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EduConnect.Api.Entities.Usuario", "VinculadoPorUsuario")
                        .WithMany()
                        .HasForeignKey("VinculadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Disciplina");

                    b.Navigation("Professor");

                    b.Navigation("Turma");

                    b.Navigation("VinculadoPorUsuario");
                });

            modelBuilder.Entity("EduConnect.Api.Entities.Usuario", b =>
                {
                    b.HasOne("EduConnect.Api.Entities.Perfil", "Perfil")
                        .WithMany("Usuarios")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("EduConnect.Api.Entities.Aluno", b =>
                {
                    b.Navigation("Frequencias");

                    b.Navigation("Notas");

                    b.Navigation("Ocorrencias");

                    b.Navigation("ResponsaveisAlunos");

                    b.Navigation("TurmasAluno");
                });

            modelBuilder.Entity("EduConnect.Api.Entities.Disciplina", b =>
                {
                    b.Navigation("ProfessorDisciplinas");

                    b.Navigation("TurmaProfessorDisciplinas");
                });

            modelBuilder.Entity("EduConnect.Api.Entities.NivelEnsino", b =>
                {
                    b.Navigation("Disciplinas");

                    b.Navigation("Turmas");
                });

            modelBuilder.Entity("EduConnect.Api.Entities.Nota", b =>
                {
                    b.Navigation("Historico");
                });

            modelBuilder.Entity("EduConnect.Api.Entities.Perfil", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("EduConnect.Api.Entities.Professor", b =>
                {
                    b.Navigation("ProfessorDisciplinas");

                    b.Navigation("TurmaProfessorDisciplinas");
                });

            modelBuilder.Entity("EduConnect.Api.Entities.Responsavel", b =>
                {
                    b.Navigation("Mensalidades");

                    b.Navigation("ResponsaveisAlunos");
                });

            modelBuilder.Entity("EduConnect.Api.Entities.Turma", b =>
                {
                    b.Navigation("EventosAgenda");

                    b.Navigation("MateriaisApoio");

                    b.Navigation("TurmaProfessorDisciplinas");

                    b.Navigation("TurmasAluno");
                });

            modelBuilder.Entity("EduConnect.Api.Entities.Usuario", b =>
                {
                    b.Navigation("Administrador");

                    b.Navigation("Aluno");

                    b.Navigation("NotificacoesEnviadas");

                    b.Navigation("NotificacoesRecebidas");

                    b.Navigation("Professor");

                    b.Navigation("Responsavel");
                });
#pragma warning restore 612, 618
        }
    }
}
